services:
  - type: web
    name: customer-management-server
    env: node
    buildCommand: rm -rf node_modules && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production